workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: 3.24.5
    scripts:
      - rm -rf android
      - flutter create . --platforms=android
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
